
import React, { useState, useEffect } from 'react';
import { 
  Moon, Sun, TrendingUp, DollarSign, Target, Sparkles, Zap, X,
  CheckCircle2, ArrowRight, Gavel, Activity, HardHat, Truck,
  Layout, PlusCircle, Download, 
  Info, MessageSquare, AlertTriangle, FileText, CheckSquare,
  Maximize2, Bot, ShieldAlert, ChevronRight, Sliders, Bell, Cpu, 
  Database, Wifi, Server, ShieldCheck, Terminal, BrainCircuit, Eye, ThumbsUp, ThumbsDown, RefreshCw, ScanLine, Loader2, Settings, Lock, AlertOctagon
} from 'lucide-react';
import { InputArea } from './components/InputArea';
import { ChartRenderer } from './components/ChartRenderer';
import { Sidebar } from './components/Sidebar';
import { generateChartResponse, Attachment } from './services/geminiService';
import { ChartConfig } from './types';
import { motion, AnimatePresence } from 'framer-motion';
import { useLiveSession } from './hooks/useLiveSession';
import { fileToBase64, getMimeType } from './utils/fileUtils';

// --- TYPES & TRANSLATIONS ---

type Language = 'en' | 'ar';
type ModalType = 'decision' | 'approval' | 'diagnostic';

const translations = {
  en: {
    appTitle: "TMG",
    subtitle: "Executive AI Command",
    live: "Live Agent",
    darkMode: "Dark Mode",
    approvals: "Pending Approvals",
    suggestedAction: "Strategic Decisions",
    kpi: "Strategic KPIs",
    priorityQueue: "Priority Focus",
    situation: "Executive Situation Report",
    agentMode: "Visual Intelligence Mode",
    close: "Close Agent",
    viewAll: "View All",
    approve: "Approve",
    reject: "Reject",
    execute: "Execute Strategy",
    defer: "Defer Decision",
    delegate: "Delegate to AI",
    details: "Details",
    settings: "Configuration",
    noPriorities: "No critical priorities.",
    noDecisions: "No pending decisions.",
    noApprovals: "No pending approvals.",
    systemStatus: "System Status",
    nominal: "All Systems Nominal",
    scanning: "Scanning Nodes...",
    runningDiagnostics: "Running Diagnostics...",
    cancel: "Cancel",
    approvalReq: "Approval Req",
    decision: "Strategic Decision",
    aiValidation: "AI Validation",
    analyze: "Analyze Content",
    scanningDocs: "Scanning Documents...",
    description: "Description",
    projectedImpact: "Projected Impact",
    totalValue: "Total Value / Cost",
    attachedDocs: "Attached Documents",
    runVariation: "Run Scenario Variation",
    addToBoard: "Add to Board",
    insights: "Executive Insights",
    recomActions: "Recommended Actions",
    genBy: "Generated by VizAgent",
    language: "Language",
    theme: "Interface Theme",
    systemConfig: "System Configuration",
    analysis: "Analysis",
    analyzing: "Analyzing Data...",
    generating: "Generating Chart...",
    failed: "Generation Failed",
    added: "Added to Board",
    aiReport: "AI Analysis Report",
    aiLayer: "AI Intelligence Layer",
    verdict: "AI Verdict",
    strategicAnalysis: "Strategic Impact Analysis",
    riskLevel: "Risk Level",
    confidence: "Confidence",
    recommended: "Recommended",
    caution: "Caution / Review",
    highRisk: "High Risk",
    docScan: "Document Scan Complete"
  },
  ar: {
    appTitle: "TMG",
    subtitle: "القيادة التنفيذية الذكية",
    live: "المساعد الذكي",
    darkMode: "الوضع الليلي",
    approvals: "الموافقات المعلقة",
    suggestedAction: "القرارات الاستراتيجية",
    kpi: "مؤشرات الأداء الاستراتيجية",
    priorityQueue: "قائمة الأولويات",
    situation: "تقرير الموقف التنفيذي",
    agentMode: "وضع الذكاء البصري",
    close: "إغلاق",
    viewAll: "عرض الكل",
    approve: "اعتماد",
    reject: "رفض",
    execute: "تنفيذ الاستراتيجية",
    defer: "تأجيل القرار",
    delegate: "توكيل الذكاء الاصطناعي",
    details: "تفاصيل",
    settings: "الإعدادات",
    noPriorities: "لا توجد أولويات حرجة",
    noDecisions: "لا توجد قرارات معلقة",
    noApprovals: "لا توجد موافقات معلقة",
    systemStatus: "حالة النظام",
    nominal: "جميع الأنظمة مستقرة",
    scanning: "جاري المسح...",
    runningDiagnostics: "تشخيص النظام...",
    cancel: "إلغاء",
    approvalReq: "طلب موافقة",
    decision: "قرار استراتيجي",
    aiValidation: "تحقق الذكاء الاصطناعي",
    analyze: "تحليل المحتوى",
    scanningDocs: "مسح المستندات...",
    description: "الوصف",
    projectedImpact: "الأثر المتوقع",
    totalValue: "القيمة الإجمالية / التكلفة",
    attachedDocs: "المستندات المرفقة",
    runVariation: "تشغيل سيناريو بديل",
    addToBoard: "إضافة إلى اللوحة",
    insights: "رؤى تنفيذية",
    recomActions: "الإجراءات الموصى بها",
    genBy: "تم الإنشاء بواسطة VizAgent",
    language: "اللغة",
    theme: "سمة الواجهة",
    systemConfig: "تكوين النظام",
    analysis: "تحليل",
    analyzing: "جاري تحليل البيانات...",
    generating: "جاري إنشاء المخطط البياني...",
    failed: "فشل الإنشاء",
    added: "تمت الإضافة إلى اللوحة",
    aiReport: "تقرير تحليل الذكاء الاصطناعي",
    aiLayer: "طبقة الذكاء الاصطناعي",
    verdict: "حكم الذكاء الاصطناعي",
    strategicAnalysis: "تحليل الأثر الاستراتيجي",
    riskLevel: "مستوى المخاطرة",
    confidence: "مستوى الثقة",
    recommended: "موصى به",
    caution: "تنبيه / مراجعة",
    highRisk: "مخاطرة عالية",
    docScan: "اكتمل مسح المستندات"
  }
};

const departmentsList = [
  { id: 'pm', en: 'Projects (Noor)', ar: 'المشاريع (مدينة نور)', icon: HardHat },
  { id: 'assets', en: 'Asset Management', ar: 'إدارة الأصول', icon: Activity }, 
  { id: 'hse', en: 'Smart City Ops', ar: 'عمليات المدن الذكية', icon: Zap }, 
  { id: 'proc', en: 'Supply Chain', ar: 'سلاسل الإمداد', icon: Truck },
  { id: 'fin', en: 'Investments', ar: 'الاستثمار والمالية', icon: DollarSign }, 
];

// --- MOCK DATA GENERATORS ---
const getDepartmentData = (deptId: string, lang: Language, customItems: any[] = []) => {
  const isEn = lang === 'en';
  
  // Base Structure
  let data = {
      kpis: [] as any[],
      situation: "",
      decisions: [] as any[],
      approvals: [] as any[],
      priorities: [] as any[]
  };

  switch (deptId) {
    case 'pm':
      data.kpis = [
          { title: isEn ? "Overall Progress" : "الإنجاز الكلي", value: "42%", sub: isEn ? "Phase 1 & 2" : "المرحلة 1 و 2", trend: "+2.4%", icon: Activity },
          { title: isEn ? "Budget Utilized" : "الميزانية المستهلكة", value: "$1.2B", sub: isEn ? "Of $4.5B CapEx" : "من 4.5 مليار", trend: "-1.2%", icon: DollarSign },
          { title: isEn ? "Workforce" : "القوى العاملة", value: "12,450", sub: isEn ? "Active on Site" : "نشط في الموقع", trend: "+540", icon: HardHat },
          { title: isEn ? "Safety Score" : "معدل الأمان", value: "99.8%", sub: isEn ? "ISO 45001 Compliant" : "مطابق للمواصفات", trend: "Stable", icon: ShieldAlert },
      ];
      data.situation = isEn 
          ? "Executive Summary: Noor City Sectors A & B represent the primary focus of Q1-Q2 operations. \n\n• Construction Velocity: proceeding 14 days ahead of schedule.\n• Supply Chain Alert: Structural steel delivery for the commercial district faces a potential 2-week delay due to logistics bottlenecks at Alexandria Port. Mitigation strategies (dual-sourcing) have been activated by the AI Procurement Agent.\n• Infrastructure: Groundwater dewatering in Sector C has been completed 100%, allowing foundation work to commence immediately.\n• Financial Health: Variance is within acceptable margins (+1.2%), with labor costs trending slightly higher due to overtime authorization." 
          : "ملخص تنفيذي: تمثل قطاعات مدينة نور (أ) و (ب) المحور الرئيسي لعمليات الربع الأول والثاني.\n\n• سرعة البناء: تسبق الجدول الزمني بـ 14 يومًا.\n• تنبيه سلاسل الإمداد: يواجه تسليم الهيكل الفولاذي للمنطقة التجارية احتمال تأخير لمدة أسبوعين بسبب اختناقات لوجستية في ميناء الإسكندرية. تم تفعيل استراتيجيات التخفيف (تعدد المصادر) بواسطة وكيل المشتريات الذكي.\n• البنية التحتية: تم الانتهاء من تجفيف المياه الجوفية في القطاع (ج) بنسبة 100٪، مما يسمح ببدء أعمال الأساسات فوراً.\n• الصحة المالية: التباين ضمن الهوامش المقبولة (+1.2٪)، مع ارتفاع طفيف في تكاليف العمالة بسبب اعتماد العمل الإضافي.";
      data.priorities = [
          { id: 'P-101', title: isEn ? "Sector B Foundation" : "أساسات القطاع ب", subtitle: isEn ? "Critical Path • 5 Days" : "مسار حرج • 5 أيام", status: "Critical", description: "Final concrete pouring for main residential tower bases.", aiVerdict: "monitor", aiAnalysis: isEn ? "Weather forecast favorable for next 72 hours. Supply chain verified." : "توقعات الطقس ملائمة لمدة 72 ساعة. تم التحقق من سلسلة التوريد." },
          { id: 'P-102', title: isEn ? "Vendor Summit" : "قمة الموردين", subtitle: isEn ? "HQ • Ballroom A" : "المقر الرئيسي • القاعة أ", status: "High", description: "Annual strategic alignment with top 20 Tier-1 suppliers.", aiVerdict: "approved", aiAnalysis: isEn ? "All logistics confirmed. Presentation deck auto-generated." : "تم تأكيد جميع الخدمات اللوجستية. تم إنشاء عرض تقديمي تلقائيًا." },
      ];
      data.approvals = [
          { 
            id: 'A-551', 
            title: isEn ? "Invoice #9921 - Orascom" : "فاتورة #9921 - أوراسكوم", 
            requester: isEn ? "Finance Dept" : "القسم المالي", 
            date: isEn ? "Today" : "اليوم", 
            type: "Payment", 
            value: "$450k", 
            description: "Milestone payment for Sector A Foundation completion.", 
            attachments: [{ name: "Invoice_9921.pdf", size: "1.2MB", type: "pdf", isMock: true }],
            aiVerdict: "safe", // safe, warning, risky
            confidence: 98,
            aiAnalysis: isEn 
              ? "Scanning Invoice #9921... \n\n• Cross-referenced with Contract #CON-2023-A: MATCH.\n• Deliverables Verification: Site logs confirm Sector A Foundation at 100% completion.\n• Pricing Check: Unit rates align with agreed BOQ.\n• Anomaly Detection: None. \n\nRecommendation: Safe to Approve."
              : "جاري مسح الفاتورة #9921...\n\n• المطابقة مع العقد #CON-2023-A: متطابق.\n• التحقق من التسليمات: سجلات الموقع تؤكد اكتمال أساسات القطاع أ بنسبة 100%.\n• فحص الأسعار: أسعار الوحدات تتوافق مع جدول الكميات المتفق عليه.\n• كشف الشذوذ: لا يوجد.\n\nالتوصية: آمن للاعتماد."
          },
          { 
            id: 'A-553', 
            title: isEn ? "Material Procurement" : "تواريد مواد خام", 
            requester: isEn ? "Supply Chain" : "سلاسل الإمداد", 
            date: isEn ? "2 Days Ago" : "منذ يومين", 
            type: "Procurement", 
            value: "$2.1M", 
            description: "Bulk order for Phase 2 structural framework.", 
            attachments: [{ name: "PO_Specs.pdf", size: "850KB", type: "pdf", isMock: true }],
            aiVerdict: "warning",
            confidence: 75,
            aiAnalysis: isEn
              ? "Scanning PO Specs... \n\n• Inventory Analysis: Current steel stock is sufficient for 4 weeks.\n• Pricing Alert: Quoted steel price is 12% higher than Q4 average.\n• Vendor History: 'SteelCorp' has a 15% delay rate in past deliveries.\n\nRecommendation: Review pricing terms before approval."
              : "جاري مسح مواصفات أمر الشراء...\n\n• تحليل المخزون: مخزون الصلب الحالي يكفي لمدة 4 أسابيع.\n• تنبيه الأسعار: سعر الصلب المقدم أعلى بنسبة 12% من متوسط الربع الرابع.\n• سجل المورد: 'SteelCorp' لديه معدل تأخير 15% في التسليمات السابقة.\n\nالتوصية: مراجعة شروط التسعير قبل الاعتماد."
          },
      ];
      data.decisions = [
          { 
            id: 'D-101', 
            title: isEn ? "Authorize Vendor Change" : "تغيير المورد المعتمد", 
            subtitle: isEn ? "Risk: Delay vs Cost" : "مخاطرة: تأخير مقابل تكلفة", 
            impact: isEn ? "Prevents 14-day delay." : "يمنع تأخير 14 يوم", 
            recommended: true, 
            description: "Switching to 'BuildMetal' incurs 2% cost premium but guarantees delivery.", 
            attachments: [{name: "Risk_Analysis.pdf", size: "2MB", type: "pdf", isMock: true}],
            aiVerdict: "recommended",
            confidence: 92,
            strategicImpact: isEn 
               ? "• Timeline: Saves 14 critical path days.\n• Budget: +$120k cost (negligible vs delay penalties).\n• Quality: BuildMetal ISO 9001 certified (Higher grade).\n• Long-term: Establishes backup supplier redundancy."
               : "• الجدول الزمني: يوفر 14 يومًا من المسار الحرج.\n• الميزانية: +120 ألف دولار تكلفة إضافية (ضئيلة مقارنة بغرامات التأخير).\n• الجودة: BuildMetal حاصلة على شهادة ISO 9001 (درجة أعلى).\n• المدى الطويل: يؤسس تكرارًا للموردين الاحتياطيين."
          },
      ];
      break;

    case 'assets':
      data.kpis = [
        { title: isEn ? "Portfolio Value" : "قيمة المحفظة", value: "$12.4B", sub: isEn ? "Total Assets" : "إجمالي الأصول", trend: "+5.1%", icon: DollarSign },
        { title: isEn ? "Occupancy Rate" : "معدل الإشغال", value: "94.2%", sub: isEn ? "Commercial & Res" : "تجاري وسكني", trend: "+0.8%", icon: Activity },
      ];
      data.situation = isEn 
        ? "Asset performance is robust. Madinaty commercial units showing 15% YoY growth in rental yields driven by new luxury retail openings. \n\nOperational Focus: Transitioning 40% of residential compound lighting to solar-hybrid systems by Q3. Expected CapEx: $4M with a 3-year ROI."
        : "أداء الأصول قوي. تظهر الوحدات التجارية في مدينتي نموًا بنسبة 15٪ سنويًا في عوائد الإيجار مدفوعة بافتتاح متاجر تجزئة فاخرة جديدة.\n\nالتركيز التشغيلي: تحويل 40٪ من إضاءة المجمعات السكنية إلى أنظمة هجينة تعمل بالطاقة الشمسية بحلول الربع الثالث. النفقات الرأسمالية المتوقعة: 4 ملايين دولار مع عائد استثمار لمدة 3 سنوات.";
      data.priorities = [{ id: 'P-201', title: isEn ? "Mall Expansion" : "توسعة المول", subtitle: isEn ? "Design Phase" : "مرحلة التصميم", status: "High", description: "Review final architectural drawings.", aiVerdict: "monitor", aiAnalysis: "Waiting for CAD files." }];
      break;
      
    // Default Fallback
    default:
       data.situation = isEn ? "All systems operational." : "جميع الأنظمة تعمل بكفاءة.";
      break;
  }

  // Merge custom items into priorities
  if (customItems.length > 0) {
      data.priorities = [...customItems, ...data.priorities];
  }

  return data;
};

// --- WIDGET COMPONENTS ---
const WidgetHeader = ({ title, icon: Icon, actionText, isDarkMode, onClick }: any) => (
  <div className="flex justify-between items-center mb-6 shrink-0">
    <div className="flex items-center gap-3">
      <div className={`p-2 rounded-lg ${isDarkMode ? 'bg-slate-800 text-brand-500' : 'bg-brand-50 text-brand-600'}`}>
        <Icon size={18} />
      </div>
      <h3 className={`text-sm font-bold uppercase tracking-widest ${isDarkMode ? 'text-slate-200' : 'text-navy-900'}`}>{title}</h3>
    </div>
    {actionText && (
      <button onClick={onClick} className={`text-xs font-bold transition-colors ${isDarkMode ? 'text-slate-500 hover:text-brand-400' : 'text-slate-400 hover:text-brand-600'}`}>
        {actionText}
      </button>
    )}
  </div>
);

const DashboardCard = ({ title, value, subtext, icon: Icon, trend, isDarkMode, onClick }: any) => (
  <div 
    onClick={onClick}
    className={`
      relative overflow-hidden rounded-2xl p-6 border transition-all duration-300 group h-full cursor-pointer
      ${isDarkMode 
        ? 'bg-slate-900/60 backdrop-blur-md border-white/5 hover:border-brand-500/30 hover:bg-slate-800/80' 
        : 'bg-white border-slate-200 hover:border-brand-400/30 hover:shadow-lg hover:-translate-y-1'
      }
    `}>
    <div className="flex justify-between items-start mb-5">
      <div className={`p-3 rounded-xl transition-colors ${isDarkMode ? 'bg-slate-800/80 text-brand-500' : 'bg-brand-50 text-brand-700'} `}>
        <Icon size={22} />
      </div>
      {trend && (
        <div className={`flex items-center gap-1 text-xs font-bold px-2.5 py-1 rounded-full ${trend.includes('+') ? 'text-emerald-500 bg-emerald-500/10' : trend === 'Stable' ? 'text-blue-500 bg-blue-500/10' : 'text-rose-500 bg-rose-500/10'}`}>
          <TrendingUp size={14} />
          {trend}
        </div>
      )}
    </div>
    <div className="space-y-1.5">
        <h3 className={`text-xs font-bold uppercase tracking-widest font-sans ${isDarkMode ? 'text-slate-400' : 'text-slate-500'}`}>{title}</h3>
        <p className={`text-3xl font-bold tracking-tight font-serif ${isDarkMode ? 'text-white' : 'text-navy-900'}`}>{value}</p>
        <p className={`text-xs font-medium ${isDarkMode ? 'text-slate-500' : 'text-slate-400'}`}>{subtext}</p>
    </div>
  </div>
);

const ListItem = ({ title, subtitle, status, value, onClick, isDarkMode, originalData }: any) => (
    <div 
      onClick={onClick}
      className={`flex items-center justify-between p-3 rounded-xl cursor-pointer transition-all border mb-2 last:mb-0 group
        ${isDarkMode 
          ? 'bg-slate-800/30 border-white/5 hover:bg-slate-800 hover:border-brand-500/30' 
          : 'bg-slate-50 border-slate-100 hover:bg-white hover:border-brand-200 hover:shadow-sm'
        }
      `}
    >
       <div className="flex flex-col min-w-0 mr-3">
           <h4 className={`text-sm font-bold truncate ${isDarkMode ? 'text-slate-200' : 'text-navy-900'}`}>{title}</h4>
           <div className="flex items-center gap-2">
              <span className={`text-xs truncate ${isDarkMode ? 'text-slate-500' : 'text-slate-500'}`}>{subtitle}</span>
              {originalData && <span className="text-[9px] bg-brand-500/20 text-brand-500 px-1.5 rounded uppercase font-bold">Chart</span>}
           </div>
       </div>
       <div className="flex flex-col items-end shrink-0">
           {value && <span className={`text-xs font-bold mb-1 ${isDarkMode ? 'text-white' : 'text-navy-900'}`}>{value}</span>}
           {status && (
             <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase
               ${status === 'Critical' ? 'bg-rose-500/10 text-rose-500' : 'bg-brand-500/10 text-brand-600'}
             `}>
               {status}
             </span>
           )}
       </div>
    </div>
);

// --- PROCESSING OVERLAY ---
const ProcessingOverlay = ({ step }: { step: string }) => (
  <motion.div 
    initial={{ opacity: 0 }} 
    animate={{ opacity: 1 }} 
    exit={{ opacity: 0 }}
    className="absolute inset-0 z-[150] flex flex-col items-center justify-center bg-black/80 backdrop-blur-xl"
  >
    <div className="w-80 h-80 relative flex items-center justify-center">
       <div className="absolute inset-0 border-t-4 border-brand-500 rounded-full animate-spin duration-[3s]"></div>
       <div className="absolute inset-6 border-r-4 border-brand-300/50 rounded-full animate-spin duration-[2s] direction-reverse"></div>
       <div className="absolute inset-12 border-l-4 border-brand-700/30 rounded-full animate-spin duration-[4s]"></div>
       <div className="relative z-10 bg-black/50 p-6 rounded-full border border-brand-500/20 backdrop-blur-md">
          <ScanLine size={48} className="text-brand-500 animate-pulse" />
       </div>
    </div>
    <motion.h2 
      key={step}
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="mt-8 text-3xl font-serif font-bold text-white tracking-widest text-center"
    >
      {step}
    </motion.h2>
  </motion.div>
);

// --- TOAST NOTIFICATION ---
const NotificationToast = ({ message, onClose, isDarkMode }: any) => (
  <motion.div 
    initial={{ opacity: 0, y: 50, scale: 0.9 }}
    animate={{ opacity: 1, y: 0, scale: 1 }}
    exit={{ opacity: 0, y: 20, scale: 0.9 }}
    className={`fixed bottom-24 right-8 z-[200] p-4 rounded-xl shadow-2xl flex items-center gap-4 border ${isDarkMode ? 'bg-slate-900 border-brand-500/50 text-white' : 'bg-white border-brand-200 text-navy-900'}`}
  >
    <div className="w-10 h-10 rounded-full bg-brand-500 flex items-center justify-center text-white shrink-0 shadow-[0_0_15px_rgba(197,160,89,0.4)]">
      <Bot size={20} />
    </div>
    <p className="text-sm font-medium">{message}</p>
    <button onClick={onClose} className="ml-2 p-2 hover:bg-white/10 rounded-full transition-colors"><X size={16}/></button>
  </motion.div>
);

// --- MODALS ---
const SettingsModal = ({ onClose, isDarkMode, toggleTheme, lang, setLang, t }: any) => {
  return (
    <div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/80 backdrop-blur-sm" onClick={onClose}>
      <motion.div 
        className={`w-full max-w-2xl rounded-2xl overflow-hidden shadow-2xl border flex flex-col max-h-[80vh] ${isDarkMode ? 'bg-slate-950 border-slate-800' : 'bg-white border-slate-200'}`} 
        onClick={e => e.stopPropagation()}
      >
        <div className="p-6 border-b border-slate-800 flex justify-between items-center bg-brand-500/5">
            <h2 className={`text-xl font-serif font-bold ${isDarkMode ? 'text-white' : 'text-navy-900'}`}>{t.systemConfig}</h2>
            <button onClick={onClose}><X size={20}/></button>
        </div>
        <div className="p-8 space-y-8 bg-slate-950 flex-1">
             <div className="flex items-center justify-between">
                 <div><h4 className="text-white font-bold">{t.language}</h4></div>
                 <div className="flex gap-2">
                     <button onClick={() => setLang('en')} className={`px-3 py-1 rounded border text-xs font-bold ${lang === 'en' ? 'bg-brand-500 text-white' : 'border-slate-700 text-slate-500'}`}>English</button>
                     <button onClick={() => setLang('ar')} className={`px-3 py-1 rounded border text-xs font-bold ${lang === 'ar' ? 'bg-brand-500 text-white' : 'border-slate-700 text-slate-500'}`}>العربية</button>
                 </div>
             </div>
             <div className="flex items-center justify-between">
                 <div><h4 className="text-white font-bold">{t.theme}</h4></div>
                 <button onClick={toggleTheme} className={`p-2 rounded-lg border ${isDarkMode ? 'bg-slate-800 border-slate-700' : 'bg-white border-slate-200'}`}>
                     {isDarkMode ? <Moon size={16} className="text-brand-500"/> : <Sun size={16}/>}
                 </button>
             </div>
        </div>
      </motion.div>
    </div>
  );
};

const DetailModal = ({ item, onClose, isDarkMode, type, onNotify, lang, onOpenDoc }: any) => {
  const t = translations[lang];

  // Verdict Helper
  const getVerdictBadge = (verdict: string) => {
    switch (verdict) {
      case 'safe':
      case 'approved':
      case 'recommended':
        return (
          <div className="flex items-center gap-2 text-emerald-500 bg-emerald-500/10 px-3 py-1.5 rounded-full border border-emerald-500/20">
            <ShieldCheck size={16} />
            <span className="text-xs font-bold uppercase tracking-wider">{t.recommended}</span>
          </div>
        );
      case 'warning':
      case 'caution':
        return (
           <div className="flex items-center gap-2 text-amber-500 bg-amber-500/10 px-3 py-1.5 rounded-full border border-amber-500/20">
             <AlertOctagon size={16} />
             <span className="text-xs font-bold uppercase tracking-wider">{t.caution}</span>
           </div>
        );
      case 'risky':
      case 'rejected':
         return (
           <div className="flex items-center gap-2 text-rose-500 bg-rose-500/10 px-3 py-1.5 rounded-full border border-rose-500/20">
             <ShieldAlert size={16} />
             <span className="text-xs font-bold uppercase tracking-wider">{t.highRisk}</span>
           </div>
         );
      default:
        return null;
    }
  };

  return (
     <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4" onClick={onClose}>
        <motion.div 
          className={`w-full max-w-3xl rounded-2xl overflow-hidden shadow-2xl border flex flex-col max-h-[90vh] ${isDarkMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'}`}
          onClick={e => e.stopPropagation()}
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
        >
            <div className="p-6 border-b border-slate-800 shrink-0 flex justify-between items-start bg-slate-950/30">
                <div>
                    <div className="flex items-center gap-3 mb-2">
                       <span className={`text-xs font-bold px-2 py-0.5 rounded uppercase tracking-wider ${isDarkMode ? 'bg-brand-500/20 text-brand-500' : 'bg-brand-50 text-brand-600'}`}>
                         {type === 'approval' ? t.approvalReq : t.decision}
                       </span>
                       {item.date && <span className="text-xs opacity-50">{item.date}</span>}
                    </div>
                    <h2 className={`text-2xl font-serif font-bold leading-tight ${isDarkMode ? 'text-white' : 'text-navy-900'}`}>{item.title}</h2>
                    {item.subtitle && <p className="text-slate-500 text-sm mt-1">{item.subtitle}</p>}
                </div>
                <button onClick={onClose} className="p-2 hover:bg-slate-800 rounded-full transition-colors"><X size={20}/></button>
            </div>
            
            <div className={`p-8 leading-relaxed space-y-8 overflow-y-auto custom-scrollbar ${isDarkMode ? 'text-slate-300' : 'text-slate-700'}`}>
                
                {/* AI INTELLIGENCE LAYER */}
                {item.aiAnalysis && (
                  <div className={`relative p-5 rounded-xl border overflow-hidden ${isDarkMode ? 'bg-slate-800/40 border-slate-700' : 'bg-brand-50/50 border-brand-200'}`}>
                     <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-brand-400 to-purple-500"></div>
                     
                     <div className="flex justify-between items-start mb-4">
                        <div className="flex items-center gap-2 text-brand-500">
                           <BrainCircuit size={20} />
                           <h3 className="font-bold text-sm uppercase tracking-widest">{t.aiLayer}</h3>
                        </div>
                        {item.aiVerdict && getVerdictBadge(item.aiVerdict)}
                     </div>

                     <div className="space-y-4">
                        <p className="whitespace-pre-line text-sm leading-relaxed opacity-90 font-medium">
                           {item.aiAnalysis}
                        </p>
                        
                        {item.strategicImpact && (
                          <div className={`mt-4 p-4 rounded-lg border border-dashed ${isDarkMode ? 'bg-slate-900/50 border-slate-700' : 'bg-white border-slate-300'}`}>
                             <h4 className="text-xs font-bold uppercase tracking-wider mb-2 opacity-70 flex items-center gap-2">
                                <Target size={14} /> {t.strategicAnalysis}
                             </h4>
                             <p className="whitespace-pre-line text-xs">{item.strategicImpact}</p>
                          </div>
                        )}
                     </div>

                     {item.confidence && (
                       <div className="mt-4 flex items-center gap-2 text-xs opacity-60 font-mono">
                          <CheckCircle2 size={12} />
                          <span>{t.confidence}: {item.confidence}%</span>
                       </div>
                     )}
                  </div>
                )}

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                        <h4 className="text-xs font-bold mb-3 opacity-50 uppercase tracking-widest">{t.description}</h4>
                        <p className="text-sm whitespace-pre-line bg-slate-950/20 p-4 rounded-lg border border-slate-800/50">{item.description}</p>
                    </div>

                    {item.attachments && (
                        <div>
                            <h4 className="text-xs font-bold mb-3 opacity-50 uppercase tracking-widest flex items-center gap-2">
                                {t.attachedDocs} <CheckCircle2 size={12} className="text-emerald-500" /> <span className="text-[10px] text-emerald-500">{t.docScan}</span>
                            </h4>
                            <div className="space-y-2">
                                {item.attachments.map((file: any, idx: number) => (
                                    <div key={idx} className={`flex items-center justify-between p-3 rounded-lg border cursor-pointer transition-colors group ${isDarkMode ? 'bg-slate-900 border-slate-800 hover:border-brand-500/30' : 'bg-white border-slate-200 hover:border-brand-300'}`}>
                                         <div className="flex items-center gap-3">
                                            <div className="p-2 rounded bg-slate-800 text-brand-500"><FileText size={16}/></div>
                                            <div>
                                              <span className={`text-sm font-bold block ${isDarkMode ? 'text-slate-200' : 'text-navy-900'}`}>{file.name}</span>
                                              <span className="text-[10px] opacity-50">{file.size}</span>
                                            </div>
                                         </div>
                                         <Eye size={16} className="opacity-0 group-hover:opacity-50" />
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}
                </div>
            </div>

            <div className={`p-6 border-t flex flex-wrap justify-end gap-3 mt-auto shrink-0 ${isDarkMode ? 'bg-slate-950 border-slate-800' : 'bg-slate-50 border-slate-200'}`}>
                {type === 'approval' ? (
                    <>
                      <button onClick={onClose} className="mr-auto px-4 py-2 rounded-lg text-slate-500 text-sm font-bold hover:bg-slate-800 transition-colors">{t.cancel}</button>
                      <button onClick={onClose} className="px-6 py-2 rounded-lg border border-rose-500/50 text-rose-500 text-sm font-bold hover:bg-rose-500/10 flex items-center gap-2">
                        <ThumbsDown size={16} /> {t.reject}
                      </button>
                      <button onClick={() => { if(onNotify) onNotify(t.aiValidation); onClose(); }} className="px-6 py-2 rounded-lg bg-emerald-600 text-white text-sm font-bold shadow-lg shadow-emerald-900/20 hover:bg-emerald-500 flex items-center gap-2">
                        <ThumbsUp size={16} /> {t.approve}
                      </button>
                    </>
                ) : (
                   <>
                     <button onClick={onClose} className="mr-auto px-4 py-2 rounded-lg text-slate-500 text-sm font-bold hover:bg-slate-800">{t.defer}</button>
                     <button onClick={() => { if(onNotify) onNotify(t.aiValidation); onClose(); }} className="px-6 py-2 rounded-lg bg-brand-600 text-white text-sm font-bold shadow-lg shadow-brand-900/20 hover:bg-brand-500 flex items-center gap-2">
                        <Gavel size={16} /> {t.execute}
                     </button>
                   </>
                )}
            </div>
        </motion.div>
     </div>
  );
};

const DocumentViewerModal = ({ file, onClose, isDarkMode }: any) => (
    <div className="fixed inset-0 z-[150] flex flex-col bg-black/95" onClick={onClose}>
        <div className="flex-1 flex items-center justify-center text-white">Document Preview</div>
    </div>
);

// --- MAIN APP ---
const App: React.FC = () => {
  const [currentChart, setCurrentChart] = useState<ChartConfig | null>(null);
  const [isDarkMode, setIsDarkMode] = useState(true); 
  const [lang, setLang] = useState<Language>('en');
  const [isLoading, setIsLoading] = useState(false);
  const [activeDept, setActiveDept] = useState('pm');
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(true);
  
  const [isProcessing, setIsProcessing] = useState(false);
  const [processingStep, setProcessingStep] = useState("");

  const [selectedItem, setSelectedItem] = useState<any | null>(null);
  const [modalType, setModalType] = useState<ModalType>('decision');
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [notification, setNotification] = useState<string | null>(null);
  const [isScanning, setIsScanning] = useState(false);
  const [activeDocument, setActiveDocument] = useState<any | null>(null);
  const [customPriorities, setCustomPriorities] = useState<any[]>([]);

  const t = translations[lang];
  const deptData = getDepartmentData(activeDept, lang, customPriorities);
  const isRtl = lang === 'ar';

  useEffect(() => {
    document.body.classList.toggle('dark', isDarkMode);
    document.body.classList.toggle('light', !isDarkMode);
  }, [isDarkMode]);

  const { connect, disconnect, isConnected, isSpeaking, volume } = useLiveSession({
    onChartGenerated: (chart) => setCurrentChart(chart),
    onNavigate: (id) => setActiveDept(id),
    lang: lang // Pass language to session
  });

  const handleSendMessage = async (text: string, file: File | null) => {
    if (isLoading) return;
    setIsLoading(true);
    
    setIsProcessing(true);
    setProcessingStep(t.analyzing);
    await new Promise(resolve => setTimeout(resolve, 800));
    setProcessingStep(t.generating);
    await new Promise(resolve => setTimeout(resolve, 800));

    try {
      let attachment: Attachment | null = null;
      if (file) {
        const base64 = await fileToBase64(file);
        attachment = { mimeType: getMimeType(file), data: base64 };
      }
      
      const chartData = await generateChartResponse(text, attachment, lang);
      setCurrentChart(chartData);

    } catch (error) {
      console.error(error);
      setNotification(t.failed);
    } finally {
      setIsLoading(false);
      setIsProcessing(false);
    }
  };

  const openModal = (item: any, type: ModalType) => {
     if (item.originalData) {
         setCurrentChart(item.originalData);
         return;
     }
     setSelectedItem(item);
     setModalType(type);
  };
  
  const runDiagnostics = () => {
    setIsScanning(true);
    setTimeout(() => {
      setIsScanning(false);
      setNotification(t.nominal);
    }, 1500);
  };

  const handleAddToBoard = () => {
     if (!currentChart) return;
     const newWidget = {
       id: `W-${Date.now()}`,
       title: currentChart.title,
       subtitle: t.aiReport,
       status: "Critical", 
       description: currentChart.summary,
       originalData: currentChart 
     };
     setCustomPriorities(prev => [newWidget, ...prev]);
     setNotification(t.added);
     setCurrentChart(null);
  };

  const glassCardClass = `
    rounded-3xl p-6 border backdrop-blur-md transition-all duration-300 h-full flex flex-col
    ${isDarkMode 
       ? 'bg-slate-900/40 border-white/5 hover:bg-slate-900/60' 
       : 'bg-white/60 border-white/60 shadow-sm hover:bg-white/80'
    }
  `;

  return (
    <div className="flex h-screen w-full relative overflow-hidden bg-transparent font-sans" dir={isRtl ? 'rtl' : 'ltr'}>
      
      <AnimatePresence>
         {isProcessing && <ProcessingOverlay step={processingStep} />}
         {activeDocument && <DocumentViewerModal file={activeDocument} onClose={() => setActiveDocument(null)} isDarkMode={isDarkMode} />}
         {selectedItem && <DetailModal item={selectedItem} type={modalType} onClose={() => setSelectedItem(null)} isDarkMode={isDarkMode} onNotify={setNotification} lang={lang} onOpenDoc={(doc: any) => setActiveDocument(doc)} />}
         {isSettingsOpen && <SettingsModal onClose={() => setIsSettingsOpen(false)} isDarkMode={isDarkMode} toggleTheme={() => setIsDarkMode(!isDarkMode)} lang={lang} setLang={setLang} t={t} />}
         {notification && <NotificationToast message={notification} onClose={() => setNotification(null)} isDarkMode={isDarkMode} />}
      </AnimatePresence>

      <Sidebar 
        departments={departmentsList}
        activeDept={activeDept}
        setActiveDept={setActiveDept}
        isCollapsed={isSidebarCollapsed}
        setIsCollapsed={setIsSidebarCollapsed}
        isDarkMode={isDarkMode}
        lang={lang}
        onSettingsClick={() => setIsSettingsOpen(true)}
      />

      <main className="flex-1 flex flex-col h-full relative z-10 overflow-hidden transition-all">
            <header className="shrink-0 px-8 md:px-10 pt-8 pb-4 flex justify-between items-center z-30">
                <div>
                    <h1 className={`text-2xl font-serif font-bold tracking-tight flex items-center gap-3 ${isDarkMode ? 'text-white' : 'text-navy-900'}`}>
                        {t.appTitle}
                    </h1>
                    <p className={`text-xs font-bold uppercase tracking-widest mt-1 ${isDarkMode ? 'text-brand-500' : 'text-brand-600'}`}>
                        {currentChart ? t.agentMode : `${t.subtitle} • ${lang === 'ar' ? departmentsList.find(d => d.id === activeDept)?.ar : departmentsList.find(d => d.id === activeDept)?.en}`}
                    </p>
                </div>
                <div className="flex items-center gap-3">
                   <button onClick={() => setLang(lang === 'en' ? 'ar' : 'en')} className={`text-xs font-bold uppercase px-3 py-2 rounded-lg ${isDarkMode ? 'text-slate-400 hover:bg-slate-800' : 'text-slate-600 hover:bg-slate-100'}`}>
                      {lang === 'en' ? 'AR' : 'EN'}
                   </button>
                    {currentChart ? (
                       <button onClick={() => setCurrentChart(null)} className="px-6 py-2.5 rounded-full bg-slate-800 text-white text-xs font-bold uppercase hover:bg-slate-700 border border-slate-600 shadow-lg flex items-center gap-2">
                          <X size={16} /> {t.close}
                       </button>
                    ) : (
                       <button onClick={() => setIsDarkMode(!isDarkMode)} className={`p-2.5 rounded-xl border transition-all ${isDarkMode ? 'border-slate-700 text-brand-500 hover:bg-slate-800' : 'border-slate-200 text-navy-900 hover:bg-slate-50'}`}>
                            {isDarkMode ? <Sun size={18} /> : <Moon size={18} />}
                       </button>
                    )}
                </div>
            </header>

            <AnimatePresence mode="wait">
            {currentChart ? (
               <motion.div 
                 key="analysis"
                 initial={{ opacity: 0, scale: 0.99 }} 
                 animate={{ opacity: 1, scale: 1 }}
                 exit={{ opacity: 0, scale: 0.99 }}
                 className="flex-1 overflow-hidden p-4 md:p-6 lg:p-8 relative flex flex-col"
               >
                  <div className="w-full h-[calc(100vh-14rem)] max-w-[1900px] mx-auto grid grid-cols-1 lg:grid-cols-12 gap-6 relative z-10 pb-4">
                     <div className="lg:col-span-8 flex flex-col h-full min-h-0 order-2 lg:order-1">
                        <div className={`flex-1 rounded-[2.5rem] p-1.5 relative group flex flex-col shadow-2xl overflow-hidden ${isDarkMode ? 'bg-gradient-to-br from-brand-500/20 via-slate-900 to-transparent' : 'bg-gradient-to-br from-brand-200 via-white to-transparent'}`}>
                           <div className={`absolute inset-0 backdrop-blur-xl rounded-[2.4rem] ${isDarkMode ? 'bg-slate-950/90' : 'bg-white/90'}`} />
                           <div className="relative h-full w-full rounded-[2.3rem] p-6 md:p-8 flex flex-col">
                              <div className="flex justify-between items-start mb-4 shrink-0">
                                 <div>
                                    <h2 className={`text-3xl font-serif font-bold tracking-tight ${isDarkMode ? 'text-white' : 'text-navy-900'}`}>{currentChart.title}</h2>
                                    <div className="flex items-center gap-3 mt-2">
                                       <span className="px-3 py-1 rounded-full bg-brand-500/10 text-brand-500 text-xs font-bold uppercase tracking-wider border border-brand-500/20 flex items-center gap-2">
                                          <BrainCircuit size={14} /> {t.genBy}
                                       </span>
                                    </div>
                                 </div>
                              </div>
                              <div className={`flex-1 w-full relative rounded-2xl overflow-hidden border border-dashed ${isDarkMode ? 'border-slate-700/20 bg-slate-900/20' : 'border-slate-300/40 bg-slate-50/50'} min-h-[400px]`}>
                                 <div className="absolute inset-0 p-4">
                                    <ChartRenderer config={currentChart} isDarkMode={isDarkMode} lang={lang} />
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div className="lg:col-span-4 flex flex-col h-full min-h-0 order-1 lg:order-2">
                        <div className={`flex-1 p-8 rounded-[2.5rem] border backdrop-blur-xl shadow-xl flex flex-col overflow-hidden relative ${isDarkMode ? 'bg-slate-900/80 border-white/10' : 'bg-white/90 border-slate-200'}`}>
                           <div className="flex items-center gap-3 mb-6 text-brand-500 shrink-0">
                              <div className="p-2 bg-brand-500/10 rounded-lg"><Sparkles size={20} /></div>
                              <h3 className="text-sm font-bold uppercase tracking-widest">{t.insights}</h3>
                           </div>
                           <div className="flex-1 overflow-y-auto custom-scrollbar pr-4 space-y-6">
                              <div className={`text-base leading-relaxed font-light whitespace-pre-wrap ${isDarkMode ? 'text-slate-300' : 'text-slate-700'}`}>
                                 {currentChart.summary.split('\n\n').map((para, i) => (
                                     <div key={i} className={`mb-4 p-4 rounded-xl border ${isDarkMode ? 'bg-slate-500/5 border-slate-500/10' : 'bg-white border-slate-100 shadow-sm'}`}>{para}</div>
                                 ))}
                              </div>
                           </div>
                           <div className="mt-6 pt-6 border-t border-dashed border-slate-700/50 space-y-3 shrink-0">
                              <h4 className={`text-xs font-bold uppercase tracking-wider mb-4 ${isDarkMode ? 'text-slate-500' : 'text-slate-400'}`}>{t.recomActions}</h4>
                              <button onClick={() => {}} className={`w-full py-3 px-5 rounded-xl border font-bold transition-all flex items-center justify-between group ${isDarkMode ? 'border-white/10 hover:bg-slate-800 text-slate-300' : 'border-slate-200 hover:bg-slate-50 text-slate-700'}`}>
                                 <span className="flex items-center gap-3 text-sm"><RefreshCw size={16} /> {t.runVariation}</span>
                                 {lang === 'ar' ? <ArrowRight size={14} className="opacity-0 group-hover:opacity-100 transition-opacity rotate-180" /> : <ArrowRight size={14} className="opacity-0 group-hover:opacity-100 transition-opacity" />}
                              </button>
                              <button onClick={handleAddToBoard} className="w-full py-3 px-5 rounded-xl bg-brand-600 text-white font-bold shadow-lg shadow-brand-500/20 hover:bg-brand-500 transition-all flex items-center justify-between group">
                                 <span className="flex items-center gap-3 text-sm"><PlusCircle size={16} /> {t.addToBoard}</span>
                                 {lang === 'ar' ? <ArrowRight size={14} className="opacity-0 group-hover:opacity-100 transition-opacity rotate-180" /> : <ArrowRight size={14} className="opacity-0 group-hover:opacity-100 transition-opacity" />}
                              </button>
                           </div>
                        </div>
                     </div>
                  </div>
               </motion.div>
            ) : (
               <div key="dashboard" className="h-full overflow-y-auto overflow-x-hidden pb-48 scroll-smooth flex-1 px-8 md:px-10 pt-4 custom-scrollbar">
                   <div className="max-w-[1920px] mx-auto flex flex-col gap-8">
                       <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                           {deptData.kpis.map((kpi: any, i: number) => (
                             <DashboardCard key={i} {...kpi} isDarkMode={isDarkMode} onClick={() => setNotification(`${t.analyze}: ${kpi.title}...`)} />
                           ))}
                       </div>
                       <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 min-h-[300px]">
                          <div className={glassCardClass + " lg:col-span-2"}>
                              <WidgetHeader title={t.situation} icon={Sparkles} isDarkMode={isDarkMode} />
                              <p className={`text-base lg:text-lg font-light leading-7 whitespace-pre-wrap ${isDarkMode?'text-slate-300':'text-slate-700'}`}>{deptData.situation}</p>
                          </div>
                          <div className={glassCardClass}>
                              <WidgetHeader title={t.priorityQueue} icon={Target} isDarkMode={isDarkMode} />
                              <div className="flex-1 overflow-y-auto custom-scrollbar pr-2">
                                {deptData.priorities.length > 0 ? deptData.priorities.map((p: any, i: number) => (
                                    <ListItem key={i} title={p.title} subtitle={p.subtitle} status={p.status} isDarkMode={isDarkMode} originalData={p.originalData} onClick={() => openModal(p, 'decision')} />
                                )) : <div className="text-center text-slate-500 text-sm py-10">{t.noPriorities}</div>}
                              </div>
                          </div>
                       </div>
                       <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 min-h-[320px]">
                          <div className={glassCardClass}>
                              <WidgetHeader title={t.suggestedAction} icon={Gavel} isDarkMode={isDarkMode} />
                              <div className="flex-1 overflow-y-auto custom-scrollbar pr-2">
                                 {deptData.decisions.length > 0 ? deptData.decisions.map((d: any, i: number) => (
                                     <ListItem key={i} title={d.title} subtitle={d.subtitle} value={d.recommended ? (lang==='ar'?'موصى به':'Recommended') : undefined} isDarkMode={isDarkMode} onClick={() => openModal(d, 'decision')} />
                                 )) : <div className="text-center text-slate-500 text-sm py-10">{t.noDecisions}</div>}
                              </div>
                          </div>
                          <div className={glassCardClass}>
                              <WidgetHeader title={t.approvals} icon={CheckSquare} isDarkMode={isDarkMode} />
                              <div className="flex-1 overflow-y-auto custom-scrollbar pr-2">
                                 {deptData.approvals.length > 0 ? deptData.approvals.map((a: any, i: number) => (
                                     <ListItem key={i} title={a.title} subtitle={a.requester} value={a.value} isDarkMode={isDarkMode} onClick={() => openModal(a, 'approval')} />
                                 )) : <div className="text-center text-slate-500 text-sm py-10">{t.noApprovals}</div>}
                              </div>
                          </div>
                          <div className={glassCardClass} onClick={runDiagnostics}>
                              <div className="flex flex-col items-center justify-center h-full text-center cursor-pointer group">
                                 <div className={`p-6 rounded-full mb-4 transition-all duration-500 ${isScanning ? 'bg-brand-500/20 shadow-[0_0_50px_rgba(197,160,89,0.3)]' : 'bg-slate-800/50 group-hover:bg-slate-800'}`}>
                                     <ShieldAlert size={48} className={`transition-all duration-500 ${isScanning ? 'animate-pulse text-brand-500' : 'text-emerald-500 group-hover:scale-110'}`} />
                                 </div>
                                 <h4 className={`text-lg font-bold mb-1 ${isDarkMode?'text-white':'text-navy-900'}`}>{isScanning ? t.runningDiagnostics : t.systemStatus}</h4>
                                 <p className={`text-sm ${isDarkMode?'text-slate-500':'text-slate-500'}`}>{isScanning ? t.scanning : t.nominal}</p>
                              </div>
                          </div>
                       </div>
                   </div>
               </div>
            )}
            </AnimatePresence>
      </main>
      <motion.div className="absolute bottom-8 left-0 right-0 z-50 flex flex-col items-center pointer-events-none px-4">
         <InputArea 
            onSendMessage={handleSendMessage}
            isLoading={isLoading}
            onConnectLive={connect}
            onDisconnectLive={disconnect}
            isLiveConnected={isConnected}
            isLiveSpeaking={isSpeaking}
            liveVolume={volume}
            isDarkMode={isDarkMode}
         />
      </motion.div>
    </div>
  );
};

export default App;
